org: hridayanp
service: projectService

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

  environment:
    TABLE_PROJECTS: projects-table-${sls:stage}
    TABLE_PROJECT_ENVS: project-envs-table-${sls:stage}
    TABLE_TASKS: tasks-table-${sls:stage}
    BUCKET_TASK_FILES: task-files-bucket-${sls:stage} # NEW for S3
    TABLE_WORKFLOWS: workflows-table-${sls:stage}
    TABLE_WORKFLOW_LOGS: workflow-logs-table-${sls:stage}
    TABLE_WORKFLOW_TASK_LOGS: workflow-task-logs-table-${sls:stage}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: '*'
        # DynamoDB permissions
        # - Effect: Allow
        #   Action:
        #     - dynamodb:PutItem
        #     - dynamodb:GetItem
        #     - dynamodb:Scan
        #     - dynamodb:UpdateItem
        #   Resource: '*'

        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_WORKFLOWS}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_WORKFLOW_LOGS}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_WORKFLOW_TASK_LOGS}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_TASKS}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_PROJECTS}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_PROJECT_ENVS}

        # S3 permissions for task files
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: arn:aws:s3:::${self:provider.environment.BUCKET_TASK_FILES}/*

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - DELETE
        - OPTIONS
      allowCredentials: false

    authorizers:
      cognitoAuth:
        type: jwt
        identitySource: '$request.header.Authorization'
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID}

functions:
  # --------------------------------------------------------
  # Tasks
  # --------------------------------------------------------
  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
          authorizer: cognitoAuth

  getTasks:
    handler: handler.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
          authorizer: cognitoAuth

  executeTask:
    handler: handler.executeTask
    events:
      - httpApi:
          path: /tasks/{taskId}/execute
          method: post
          authorizer: cognitoAuth

  getTaskLogFile:
    handler: handler.getTaskLogFile
    events:
      - httpApi:
          path: /tasks/{taskId}/logs
          method: get
          authorizer: cognitoAuth

  getTaskScriptFiles:
    handler: handler.getTaskScriptFiles
    events:
      - httpApi:
          path: /tasks/{taskId}/files
          method: get
          authorizer: cognitoAuth

  # --------------------------------------------------------
  # Projects
  # --------------------------------------------------------
  createProject:
    handler: handler.createProject
    events:
      - httpApi:
          path: /project
          method: post
          authorizer: cognitoAuth

  getProjects:
    handler: handler.getProjects
    events:
      - httpApi:
          path: /project
          method: get
          authorizer: cognitoAuth
  deleteProject:
    handler: handler.deleteProject
    events:
      - httpApi:
          path: /project/{projectId}
          method: delete
          authorizer: cognitoAuth

  # --------------------------------------------------------
  # Environments
  # --------------------------------------------------------
  createEnvironment:
    handler: handler.createEnvironment
    events:
      - httpApi:
          path: /project/environment
          method: post
          authorizer: cognitoAuth

  getEnvironments:
    handler: handler.getEnvironments
    events:
      - httpApi:
          path: /project/environment/{projectId}
          method: get
          authorizer: cognitoAuth

  # --------------------------------------------------------
  # Workflows
  # --------------------------------------------------------
  createWorkflow:
    handler: handler.createWorkflow
    events:
      - httpApi:
          path: /workflows
          method: post
          authorizer: cognitoAuth

  getWorkflows:
    handler: handler.getWorkflows
    events:
      - httpApi:
          path: /workflows
          method: get
          authorizer: cognitoAuth

  executeWorkflow:
    handler: handler.executeWorkflow
    events:
      - httpApi:
          path: /workflows/{workflow_id}/execute
          method: post
          authorizer: cognitoAuth

  fetchWorkflowLogs:
    handler: handler.fetchWorkflowLogs
    events:
      - httpApi:
          path: /workflows/logs
          method: post
          authorizer: cognitoAuth

  # --------------------------------------------------------
  # Workflow Executor (async / internal)
  # --------------------------------------------------------
  workflowExecutor:
    handler: src/workers/workflowExecutor.handler
    timeout: 900

# ------------------------------------------------------------
# DynamoDB Tables
# ------------------------------------------------------------
resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_TASKS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PROJECTS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ProjectEnvsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PROJECT_ENVS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TaskFilesBucket: # Optional if you want CloudFormation to create the S3 bucket
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_TASK_FILES}

    WorkflowsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_WORKFLOWS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    WorkflowLogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_WORKFLOW_LOGS}
        AttributeDefinitions:
          - AttributeName: run_id
            AttributeType: S
        KeySchema:
          - AttributeName: run_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    WorkflowTaskLogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_WORKFLOW_TASK_LOGS}
        AttributeDefinitions:
          - AttributeName: run_id
            AttributeType: S
          - AttributeName: task_id
            AttributeType: S
        KeySchema:
          - AttributeName: run_id
            KeyType: HASH
          - AttributeName: task_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
