org: hridayanp
service: projectService

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

  environment:
    TABLE_PROJECTS: projects-table-${sls:stage}
    TABLE_PROJECT_ENVS: project-envs-table-${sls:stage}
    TABLE_TASKS: tasks-table-${sls:stage}
    BUCKET_TASK_FILES: task-files-bucket-${sls:stage} # NEW for S3
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}

  iam:
    role:
      statements:
        # DynamoDB permissions
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource: '*'

        # S3 permissions for task files
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: arn:aws:s3:::${self:provider.environment.BUCKET_TASK_FILES}/*

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: false

    authorizers:
      cognitoAuth:
        type: jwt
        identitySource: '$request.header.Authorization'
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID}

functions:
  # --------------------------------------------------------
  # Tasks
  # --------------------------------------------------------
  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
          authorizer: cognitoAuth

  getTasks:
    handler: handler.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
          authorizer: cognitoAuth

  executeTask:
    handler: handler.executeTask
    events:
      - httpApi:
          path: /tasks/{taskId}/execute
          method: post
          authorizer: cognitoAuth

  getTaskLogFile:
    handler: handler.getTaskLogFile
    events:
      - httpApi:
          path: /tasks/{taskId}/logs
          method: get
          authorizer: cognitoAuth

  getTaskScriptFiles:
    handler: handler.getTaskScriptFiles
    events:
      - httpApi:
          path: /tasks/{taskId}/files
          method: get
          authorizer: cognitoAuth

  # --------------------------------------------------------
  # Projects
  # --------------------------------------------------------
  createProject:
    handler: handler.createProject
    events:
      - httpApi:
          path: /project
          method: post
          authorizer: cognitoAuth

  getProjects:
    handler: handler.getProjects
    events:
      - httpApi:
          path: /project
          method: get
          authorizer: cognitoAuth

  # --------------------------------------------------------
  # Environments
  # --------------------------------------------------------
  createEnvironment:
    handler: handler.createEnvironment
    events:
      - httpApi:
          path: /project/environment
          method: post
          authorizer: cognitoAuth

  getEnvironments:
    handler: handler.getEnvironments
    events:
      - httpApi:
          path: /project/environment/{projectId}
          method: get
          authorizer: cognitoAuth

# ------------------------------------------------------------
# DynamoDB Tables
# ------------------------------------------------------------
resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_TASKS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PROJECTS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ProjectEnvsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_PROJECT_ENVS}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TaskFilesBucket: # Optional if you want CloudFormation to create the S3 bucket
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_TASK_FILES}
